export const INDIAN_COLLEGES = [
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Kanpur",
  "Indian Institute of Technology (IIT) Kharagpur",
  "Indian Institute of Technology (IIT) Madras",
  "Indian Institute of Technology (IIT) Roorkee",
  "Indian Institute of Technology (IIT) Guwahati",
  "Indian Institute of Technology (IIT) Hyderabad",
  "National Institute of Technology (NIT) Trichy",
  "National Institute of Technology (NIT) Surathkal",
  "National Institute of Technology (NIT) Warangal",
  "National Institute of Technology (NIT) Calicut",
  "National Institute of Technology (NIT) Rourkela",
  "Motilal Nehru National Institute of Technology (MNNIT) Allahabad",
  "Malaviya National Institute of Technology (MNIT) Jaipur",
  "Visvesvaraya National Institute of Technology (VNIT) Nagpur",
  "Indian Institute of Information Technology (IIIT) Hyderabad",
  "Indian Institute of Information Technology (IIIT) Bangalore",
  "Indian Institute of Information Technology (IIIT) Allahabad",
  "Indian Institute of Information Technology (IIIT) Delhi",
  "Birla Institute of Technology and Science (BITS) Pilani",
  "Vellore Institute of Technology (VIT)",
  "SRM Institute of Science and Technology",
  "Manipal Institute of Technology (MIT)",
  "Kalinga Institute of Industrial Technology (KIIT)",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "Jadavpur University",
  "Anna University",
  "University of Delhi (DU)",
  "University of Mumbai",
  "Savitribai Phule Pune University (SPPU)",
  "Christ University",
  "NMIMS",
  "Symbiosis International University",
  "Thapar Institute of Engineering and Technology",
  "PSG College of Technology",
  "RV College of Engineering",
  "BMS College of Engineering",
  "MS Ramaiah Institute of Technology",
  "VJTI Mumbai",
  "College of Engineering Pune (COEP)",
  "LD College of Engineering",
  "Nirma University"
];
